# Generated by Django 2.1.4 on 2019-04-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
